[package]
name = "zed-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "=1.0.86"
gix = { version = "0.79.0", features = ["blocking-network-client", "blocking-http-transport-reqwest", "blocking-http-transport-reqwest-rust-tls"] }
imara-diff = "0.2.0"
lsp-types = { git = "https://github.com/zed-industries/lsp-types.git", rev = "a4f410987660bf560d1e617cb78117c6b6b9f599", version = "0.95.1" }
rand = "0.10.0"
rustc-hash = "=2.1.0"
smallvec = "1.6"
tempfile = "3.25.0"

[lints.clippy]
pedantic = "warn"

[dev-dependencies]
criterion = "0.8.2"
criterion-macro = "0.4.0"

[[bench]]
name = "benchmark"
