[package]
name = "zed-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "=1.0.86"
lsp-types = { git = "https://github.com/zed-industries/lsp-types.git", rev = "a4f410987660bf560d1e617cb78117c6b6b9f599", version = "0.95.1" }
rustc-hash = "=2.1.0"
smallvec = "=1.6"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "benchmark"
harness = false
